// ==========================================================
// js/slides.js
// Contenido de las diapositivas, en el mismo orden de
// step_by_step.md. El código NO se escribe aquí: cada editor
// apunta a un archivo real (js/code-files.js) y a un rango de
// líneas, para que las diapositivas nunca se desincronicen
// del proyecto.
//
// Campos principales de cada diapositiva:
//   step     -> número de paso en step_by_step.md
//   part     -> { n, of, label } cuando un archivo largo se divide
//   phase    -> grupo del índice
//   layer    -> etiqueta de la capa (carpeta)
//   lead     -> párrafos de explicación (admite <code> y <strong>)
//   commands -> comandos de terminal
//   visual   -> panel derecho (editor, terminal, árbol, etc.)
//   flow     -> qué nodos del recorrido se iluminan y cómo se animan
//   bubble   -> lo que narra Bit (punto clave)
//   mood     -> expresión de Bit
//
// Los mensajes de la API y las salidas de consola se copian tal
// cual los imprime el código (sin tildes), para que coincidan
// exactamente con lo que verán los estudiantes.
// ==========================================================

window.PHASES = [
  { id: 'inicio', label: 'Inicio' },
  { id: 'fundamentos', label: 'Fundamentos' },
  { id: 'proyecto', label: 'Proyecto Node.js' },
  { id: 'utils', label: 'Utilidades (utils/)' },
  { id: 'modelo', label: 'Modelo y conexión' },
  { id: 'capas', label: 'Capas de la API' },
  { id: 'probar', label: 'Probar y cerrar' },
];

// Nodos del recorrido de una petición (franja superior)
window.PIPELINE = {
  main: [
    { id: 'cliente', label: 'Cliente', hint: 'curl, Postman o un frontend' },
    { id: 'express', label: 'Express', hint: 'index.js + config/app.js' },
    { id: 'routes', label: 'routes/', hint: 'persona.routes.js' },
    { id: 'controllers', label: 'controllers/', hint: 'persona.controller.js' },
    { id: 'services', label: 'services/', hint: 'persona.service.js' },
    { id: 'models', label: 'models/', hint: 'Persona.js' },
    { id: 'mysql', label: 'MySQL', hint: 'config/database.js + persona_db' },
  ],
  side: [
    { id: 'utils', label: 'utils/', hint: 'validadores, fechas, constantes', link: 'services' },
    { id: 'middleware', label: 'middleware/', hint: 'manejo de errores', link: 'express' },
  ],
};

// Filas del diagrama grande de arquitectura (pasos 0 y 24)
window.ARCHITECTURE = {
  main: [
    { id: 'cliente', label: 'Cliente', note: 'curl / Postman / frontend' },
    { id: 'express', label: 'index.js + config/app.js', note: 'arranca el servidor y monta las rutas' },
    { id: 'routes', label: 'routes/', note: 'define los endpoints (URLs + verbo HTTP)' },
    { id: 'controllers', label: 'controllers/', note: 'recibe la petición HTTP, llama al service, responde' },
    { id: 'services', label: 'services/', note: 'lógica de negocio: valida, arma el objeto Persona y ejecuta el CRUD' },
    { id: 'models', label: 'models/', note: 'clase Persona (entidad del dominio)' },
    { id: 'mysql', label: 'config/database', note: 'pool de conexiones a MySQL' },
  ],
  side: [
    { id: 'middleware', label: 'middleware/', note: 'manejo de errores', row: 'express' },
    { id: 'utils', label: 'utils/', note: 'validadores, fechas, constantes, mensajes', row: 'services' },
  ],
};

const TREE_INITIAL = [
  { name: 'persona-api', type: 'dir', depth: 0 },
  { name: 'config', type: 'dir', depth: 1 },
  { name: 'controllers', type: 'dir', depth: 1 },
  { name: 'middleware', type: 'dir', depth: 1 },
  { name: 'models', type: 'dir', depth: 1 },
  { name: 'routes', type: 'dir', depth: 1 },
  { name: 'services', type: 'dir', depth: 1 },
  { name: 'utils', type: 'dir', depth: 1 },
  { name: 'database.sql', type: 'file', depth: 1 },
  { name: 'package.json', type: 'file', depth: 1 },
];

// Notas tomadas del árbol final de step_by_step.md (paso 24)
const TREE_FINAL = [
  { name: 'persona-api', type: 'dir', depth: 0 },
  { name: 'config', type: 'dir', depth: 1 },
  { name: 'app.js', type: 'file', depth: 2, note: 'Configuracion de Express (middlewares + rutas)' },
  { name: 'database.js', type: 'file', depth: 2, note: 'Clase de conexion a MySQL (pool)' },
  { name: 'env.js', type: 'file', depth: 2, note: 'Carga y valida las variables de entorno' },
  { name: 'controllers', type: 'dir', depth: 1 },
  { name: 'persona.controller.js', type: 'file', depth: 2, note: 'Logica de entrada/salida HTTP' },
  { name: 'middleware', type: 'dir', depth: 1 },
  { name: 'errorHandler.js', type: 'file', depth: 2, note: 'Manejo centralizado de errores' },
  { name: 'models', type: 'dir', depth: 1 },
  { name: 'Persona.js', type: 'file', depth: 2, note: 'Entidad Persona (POO, getters/setters)' },
  { name: 'postman', type: 'dir', depth: 1 },
  { name: 'Persona_API.postman_collection.json', type: 'file', depth: 2 },
  { name: 'routes', type: 'dir', depth: 1 },
  { name: 'persona.routes.js', type: 'file', depth: 2, note: 'Definicion de endpoints' },
  { name: 'services', type: 'dir', depth: 1 },
  { name: 'persona.service.js', type: 'file', depth: 2, note: 'Logica de negocio + CRUD contra MySQL' },
  { name: 'utils', type: 'dir', depth: 1 },
  { name: 'AppError.js', type: 'file', depth: 2, note: 'Clase de error personalizada' },
  { name: 'constants.js', type: 'file', depth: 2, note: 'Codigos HTTP y reglas de negocio' },
  { name: 'dateFormatter.js', type: 'file', depth: 2, note: 'Formateo de fechas' },
  { name: 'validators.js', type: 'file', depth: 2, note: 'Validadores de los campos de Persona' },
  { name: '.env', type: 'file', depth: 1, note: 'Variables de entorno reales (NO se sube a git)', muted: true },
  { name: '.env.example', type: 'file', depth: 1, note: 'Plantilla de variables de entorno' },
  { name: '.gitignore', type: 'file', depth: 1 },
  { name: 'database.sql', type: 'file', depth: 1, note: 'Script de creacion de la BD y la tabla' },
  { name: 'index.js', type: 'file', depth: 1, note: 'Punto de entrada: arranca el servidor' },
  { name: 'package.json', type: 'file', depth: 1 },
  { name: 'step_by_step.md', type: 'file', depth: 1, note: 'Esta guia' },
];

const PERSONA_JUAN = { id: 1, firstname: 'Juan', lastname: 'Perez', age: 28, datebirth: '1997-05-20' };
const PERSONA_MARIA = { id: 2, firstname: 'Maria', lastname: 'Gomez', age: 34, datebirth: '1991-11-03' };

// Peticiones del paso 22. Las respuestas son ejemplos coherentes con
// los datos de database.sql y con los mensajes reales del controller.
const REQUESTS = [
  {
    id: 'post',
    method: 'POST',
    path: '/api/personas',
    label: 'Crear una persona',
    curl: 'curl -X POST http://localhost:3000/api/personas \\\n  -H "Content-Type: application/json" \\\n  -d \'{"firstname":"Juan","lastname":"Perez","age":28,"datebirth":"1997-05-20"}\'',
    status: 201,
    statusText: 'Created',
    response: {
      success: true,
      message: 'Persona creada exitosamente.',
      data: { id: 3, firstname: 'Juan', lastname: 'Perez', age: 28, datebirth: '1997-05-20' },
    },
  },
  {
    id: 'get-all',
    method: 'GET',
    path: '/api/personas',
    label: 'Listar todas las personas',
    curl: 'curl http://localhost:3000/api/personas',
    status: 200,
    statusText: 'OK',
    response: {
      success: true,
      message: 'Personas obtenidas exitosamente.',
      data: [
        PERSONA_JUAN,
        PERSONA_MARIA,
        { id: 3, firstname: 'Juan', lastname: 'Perez', age: 28, datebirth: '1997-05-20' },
      ],
    },
  },
  {
    id: 'get-one',
    method: 'GET',
    path: '/api/personas/1',
    label: 'Obtener una persona por id',
    curl: 'curl http://localhost:3000/api/personas/1',
    status: 200,
    statusText: 'OK',
    response: { success: true, message: 'Persona obtenida exitosamente.', data: PERSONA_JUAN },
  },
  {
    id: 'put',
    method: 'PUT',
    path: '/api/personas/1',
    label: 'Actualizar una persona',
    curl: 'curl -X PUT http://localhost:3000/api/personas/1 \\\n  -H "Content-Type: application/json" \\\n  -d \'{"firstname":"Juan","lastname":"Perez Actualizado","age":29,"datebirth":"1997-05-20"}\'',
    status: 200,
    statusText: 'OK',
    response: {
      success: true,
      message: 'Persona actualizada exitosamente.',
      data: { id: 1, firstname: 'Juan', lastname: 'Perez Actualizado', age: 29, datebirth: '1997-05-20' },
    },
  },
  {
    id: 'delete',
    method: 'DELETE',
    path: '/api/personas/1',
    label: 'Eliminar una persona',
    curl: 'curl -X DELETE http://localhost:3000/api/personas/1',
    status: 200,
    statusText: 'OK',
    response: { success: true, message: 'Persona eliminada exitosamente.', data: null },
  },
  {
    id: 'post-error',
    method: 'POST',
    path: '/api/personas',
    label: 'Crear con un dato inválido',
    curl: 'curl -X POST http://localhost:3000/api/personas \\\n  -H "Content-Type: application/json" \\\n  -d \'{"firstname":"Juan","lastname":"Perez","age":"abc","datebirth":"1997-05-20"}\'',
    status: 400,
    statusText: 'Bad Request',
    error: true,
    response: { success: false, message: 'El campo "age" debe ser un numero entero entre 1 y 120.' },
  },
];

window.SLIDES = [
  // ---------------------------------------------------------- PORTADA
  {
    id: 'inicio',
    kind: 'cover',
    phase: 'inicio',
    title: 'Persona API',
    kicker: 'Taller de backend con JavaScript',
    lead: [
      'Construye paso a paso una <strong>API REST</strong> para crear, leer, actualizar y eliminar personas con <strong>Node.js</strong>, <strong>Express</strong> y <strong>MySQL</strong>.',
    ],
    meta: ['26 pasos', '18 archivos', '5 endpoints'],
    visual: {
      type: 'editor',
      caption: 'Al final del taller, tu API responderá así a un POST:',
      tabs: [{ title: 'respuesta 201', lang: 'json', text: JSON.stringify(REQUESTS[0].response, null, 2), status: 'JSON · 201 Created' }],
    },
    flow: { lit: ['cliente', 'express', 'routes', 'controllers', 'services', 'models', 'mysql'], mode: 'boot' },
    bubble: { title: 'Hola, soy Bit', text: 'Te acompaño a construir la API de Persona capa por capa. Avanza con las flechas del teclado o con los botones de abajo.' },
    mood: 'wave',
  },

  // ---------------------------------------------------------- FUNDAMENTOS
  {
    id: 'paso-0',
    step: 0,
    phase: 'fundamentos',
    layer: 'objetivo',
    title: 'Objetivo del proyecto',
    lead: [
      'Construir una <strong>API REST</strong> con <strong>Node.js + Express + MySQL</strong> que permita <strong>crear, leer, actualizar y eliminar (CRUD)</strong> el registro de una <code>Persona</code> con estos datos:',
    ],
    table: {
      head: ['Campo', 'Tipo', 'Descripción'],
      rows: [
        ['<code>id</code>', 'entero', 'Identificador único (autoincremental)'],
        ['<code>firstname</code>', 'texto', 'Nombre de la persona'],
        ['<code>lastname</code>', 'texto', 'Apellido de la persona'],
        ['<code>age</code>', 'entero', 'Edad de la persona'],
        ['<code>datebirth</code>', 'fecha', 'Fecha de nacimiento (<code>YYYY-MM-DD</code>)'],
      ],
    },
    visual: { type: 'architecture' },
    flow: { lit: [], mode: 'full' },
    bubble: { text: 'La aplicación se organiza en capas: cada carpeta tiene una sola responsabilidad. middleware/ y utils/ son transversales, las usan varias capas.' },
  },
  {
    id: 'paso-1',
    step: 1,
    phase: 'fundamentos',
    layer: 'terminal',
    title: 'Prerrequisitos',
    lead: ['Antes de empezar, confirma en una terminal que tienes instalado lo siguiente:'],
    checklist: [
      { name: 'Node.js', detail: 'Versión 18 o superior', cmd: 'node -v' },
      { name: 'npm', detail: 'Viene incluido con Node.js', cmd: 'npm -v' },
      { name: 'MySQL', detail: 'Servidor instalado y corriendo', cmd: 'mysql --version' },
    ],
    visual: {
      type: 'terminal',
      commands: [{ code: 'node -v      # Node.js 18 o superior\nnpm -v       # npm viene incluido con Node.js\nmysql --version   # Cliente/servidor de MySQL' }],
    },
    flow: { lit: [], mode: 'idle' },
    bubble: { text: 'Se asume que ya tienes un servidor MySQL instalado y corriendo en tu máquina, y que conoces el usuario y la contraseña con los que te conectas.' },
  },
  {
    id: 'paso-2',
    step: 2,
    phase: 'fundamentos',
    layer: 'MySQL',
    title: 'Crear la base de datos y la tabla',
    file: 'database.sql',
    lead: [
      'Antes de escribir una sola línea de Node.js, preparamos la base de datos. Guarda este script como <code>database.sql</code> en la raíz del proyecto.',
    ],
    commands: [{ label: 'Ejecuta el script (te pedirá la contraseña de tu usuario de MySQL)', code: 'mysql -u root -p < database.sql' }],
    visual: { type: 'editor', tabs: [{ file: 'database.sql', lang: 'sql', focus: [[15, 21]] }] },
    flow: { lit: ['mysql'], mode: 'idle' },
    bubble: { text: 'La tabla se llama personas (plural, en minúscula) y la clase de JavaScript se llamará Persona (singular, PascalCase). El id es AUTO_INCREMENT: MySQL lo genera en cada INSERT.' },
  },

  // ---------------------------------------------------------- PROYECTO NODE.JS
  {
    id: 'paso-3',
    step: 3,
    phase: 'proyecto',
    layer: 'npm',
    title: 'Inicializar el proyecto de Node.js',
    lead: ['Crea la carpeta del proyecto, inicializa <code>package.json</code> y crea la estructura de carpetas que vamos a usar.'],
    commands: [
      { label: 'Crea la carpeta del proyecto y entra en ella', code: 'mkdir persona-api\ncd persona-api' },
      { label: 'Inicializa package.json', code: 'npm init -y' },
      { label: 'Crea la estructura de carpetas', code: 'mkdir config controllers middleware models routes services utils' },
    ],
    visual: { type: 'explorer', title: 'Estructura al terminar este paso', tree: TREE_INITIAL },
    flow: { lit: ['routes', 'controllers', 'services', 'models', 'utils', 'middleware'], mode: 'boot' },
    bubble: { text: 'npm init -y crea package.json con valores por defecto. Cada carpeta que creas aquí será una capa de la API.' },
  },
  {
    id: 'paso-4',
    step: 4,
    phase: 'proyecto',
    layer: 'npm',
    title: 'Instalar las dependencias',
    lead: [
      '<strong>Dependencias de producción:</strong> las necesita la app para funcionar.',
      '<strong>Dependencia de desarrollo:</strong> solo para programar, no en producción.',
    ],
    commands: [
      { label: 'Producción', code: 'npm install express mysql2 dotenv cors morgan' },
      { label: 'Desarrollo', code: 'npm install -D nodemon' },
    ],
    visual: {
      type: 'packages',
      rows: [
        ['express', 'Framework web para crear el servidor y las rutas de la API'],
        ['mysql2', 'Driver para conectar Node.js con MySQL (usamos su versión promise)'],
        ['dotenv', 'Carga variables de entorno desde un archivo .env'],
        ['cors', 'Habilita peticiones desde otros orígenes (otro puerto o dominio)'],
        ['morgan', 'Middleware de logging: imprime cada petición HTTP en la consola'],
        ['nodemon', 'Reinicia el servidor automáticamente al guardar cambios', 'dev'],
      ],
    },
    flow: { lit: ['express', 'mysql'], mode: 'idle' },
    bubble: { text: 'nodemon reinicia el servidor cada vez que guardas un cambio, así no tienes que detener y volver a ejecutar node index.js a mano.' },
  },
  {
    id: 'paso-5',
    step: 5,
    phase: 'proyecto',
    layer: 'npm',
    title: 'Configurar los scripts de package.json',
    file: 'package.json',
    lead: ['Edita <code>package.json</code> y agrega la sección <code>"scripts"</code>.'],
    list: [
      '<code>npm start</code> ejecuta la app con <code>node</code> (modo "producción").',
      '<code>npm run dev</code> ejecuta la app con <code>nodemon</code> (modo "desarrollo", con recarga automática).',
    ],
    visual: { type: 'editor', tabs: [{ file: 'package.json', lang: 'json', focus: [[6, 9]] }] },
    flow: { lit: ['express'], mode: 'idle' },
    bubble: { text: 'Con los scripts no tienes que memorizar comandos largos: npm run dev mientras programas y npm start en producción.' },
  },
  {
    id: 'paso-6',
    step: 6,
    phase: 'proyecto',
    layer: 'entorno',
    title: 'Variables de entorno: .env y .gitignore',
    file: '.env.example',
    lead: [
      'Las credenciales de la base de datos <strong>nunca</strong> se escriben directamente en el código. Se guardan en un archivo <code>.env</code> que <strong>no se sube a git</strong>.',
      'Crea <code>.env.example</code> (este sí se sube, sirve de plantilla) y <code>.gitignore</code>.',
    ],
    commands: [{ label: 'Crea tu .env real copiando la plantilla y pon tu contraseña de MySQL', code: 'cp .env.example .env' }],
    visual: {
      type: 'editor',
      tabs: [
        { file: '.env.example', lang: 'ini', focus: [[10, 16]] },
        { file: '.gitignore', lang: 'bash', focus: [[4, 5]] },
      ],
    },
    flow: { lit: ['mysql'], mode: 'idle' },
    bubble: { text: 'El .env real, con tu contraseña, queda fuera del repositorio gracias a .gitignore. Tus compañeros usan .env.example para crear el suyo.' },
  },

  // ---------------------------------------------------------- UTILS
  {
    id: 'paso-7',
    step: 7,
    phase: 'utils',
    layer: 'utils/',
    title: 'Constantes generales',
    file: 'utils/constants.js',
    lead: ['Empezamos por <code>utils/</code> porque el resto de las capas dependen de estas constantes y mensajes compartidos.'],
    commands: [{ code: 'touch utils/constants.js' }],
    visual: { type: 'editor', tabs: [{ file: 'utils/constants.js', lang: 'javascript', focus: [[9, 16]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'Centralizar los códigos HTTP evita los "números mágicos": en vez de un 404 suelto escribes CODIGOS_HTTP.NO_ENCONTRADO y el código se explica solo.' },
  },
  {
    id: 'paso-8',
    step: 8,
    phase: 'utils',
    layer: 'utils/',
    title: 'Mensajes de error centralizados',
    file: 'utils/errorMessages.js',
    lead: ['Mensajes de error en español, en un solo lugar. Así no se duplica texto y es fácil ajustar el idioma de la API en el futuro.'],
    commands: [{ code: 'touch utils/errorMessages.js' }],
    visual: { type: 'editor', tabs: [{ file: 'utils/errorMessages.js', lang: 'javascript', focus: [[8, 14]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'Si mañana cambias un mensaje, lo cambias aquí una sola vez y se actualiza en toda la API.' },
  },
  {
    id: 'paso-9',
    step: 9,
    phase: 'utils',
    layer: 'utils/',
    title: 'Clase de error personalizada',
    file: 'utils/AppError.js',
    lead: ['Una clase para los errores <strong>operacionales</strong>: los esperados, como validaciones o recursos no encontrados. Así se diferencian de los errores de programación (bugs).'],
    commands: [{ code: 'touch utils/AppError.js' }],
    visual: { type: 'editor', tabs: [{ file: 'utils/AppError.js', lang: 'javascript', focus: [[9, 18]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'AppError extiende de Error (herencia de clases). Cuando un service lanza throw new AppError(...), el middleware sabe que es un error esperado gracias a esOperacional.' },
    mood: 'surprised',
  },
  {
    id: 'paso-10',
    step: 10,
    phase: 'utils',
    layer: 'utils/',
    title: 'Formateo de fechas',
    file: 'utils/dateFormatter.js',
    lead: ['Funciones utilitarias para fechas. La tabla guarda <code>datebirth</code> como tipo <code>DATE</code> en formato <code>YYYY-MM-DD</code>, que es el formato que espera MySQL.'],
    commands: [{ code: 'touch utils/dateFormatter.js' }],
    visual: { type: 'editor', tabs: [{ file: 'utils/dateFormatter.js', lang: 'javascript', focus: [[14, 20]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'formatearFechaLegible("1997-05-20") devuelve "20/05/1997". El service la usa para mostrar la fecha en la consola al crear una persona.' },
  },
  {
    id: 'paso-11-1',
    step: 11,
    part: { n: 1, of: 3, label: 'Expresiones regulares, texto y edad' },
    phase: 'utils',
    layer: 'utils/',
    title: 'Validadores personalizados',
    file: 'utils/validators.js',
    lead: ['Validadores para los datos de Persona. Se usan desde <code>services</code> <strong>antes</strong> de tocar la base de datos: nunca confíes en los datos que llegan del cliente (<code>req.body</code>).'],
    commands: [{ code: 'touch utils/validators.js' }],
    visual: { type: 'editor', tabs: [{ file: 'utils/validators.js', lang: 'javascript', range: [1, 37], focus: [[11, 15]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'REGEX_SOLO_LETRAS acepta letras con tilde, la ñ y espacios. Así "María José" es válido, pero "M4ría" no.' },
  },
  {
    id: 'paso-11-2',
    step: 11,
    part: { n: 2, of: 3, label: 'Fecha e id' },
    phase: 'utils',
    layer: 'utils/',
    title: 'Validadores personalizados',
    file: 'utils/validators.js',
    lead: [
      '<code>esFechaValida</code> exige el formato <code>YYYY-MM-DD</code>, una fecha real y que no sea futura.',
      '<code>esIdValido</code> revisa que el id de la URL sea un entero positivo.',
    ],
    visual: { type: 'editor', tabs: [{ file: 'utils/validators.js', lang: 'javascript', range: [39, 55], focus: [[52, 55]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'Ojo: los parámetros de la URL siempre llegan como texto. Por eso esIdValido convierte el valor con Number() antes de validarlo.' },
    mood: 'think',
  },
  {
    id: 'paso-11-3',
    step: 11,
    part: { n: 3, of: 3, label: 'validarDatosPersona' },
    phase: 'utils',
    layer: 'utils/',
    title: 'Validadores personalizados',
    file: 'utils/validators.js',
    lead: ['Valida el objeto completo que llega en el body de un <code>POST</code> o <code>PUT</code> y devuelve el resultado junto con la lista de errores.'],
    visual: { type: 'editor', tabs: [{ file: 'utils/validators.js', lang: 'javascript', range: [57, 88], focus: [[60, 61], [79, 79]] }] },
    flow: { lit: ['utils'], mode: 'idle' },
    bubble: { text: 'validarDatosPersona no lanza errores: devuelve { esValido, errores }. El service decide qué hacer con esa lista.' },
  },

  // ---------------------------------------------------------- MODELO Y CONEXIÓN
  {
    id: 'paso-12-1',
    step: 12,
    part: { n: 1, of: 3, label: 'Campos privados y constructor' },
    phase: 'modelo',
    layer: 'models/',
    title: 'La entidad Persona (POO)',
    file: 'models/Persona.js',
    lead: ['La clase <code>Persona</code> representa el objeto de negocio de toda la aplicación. Usa atributos privados con <code>#</code>, la sintaxis nativa de JavaScript para campos privados.'],
    commands: [{ code: 'touch models/Persona.js' }],
    visual: { type: 'editor', tabs: [{ file: 'models/Persona.js', lang: 'javascript', range: [1, 24], focus: [[10, 14]] }] },
    flow: { lit: ['models'], mode: 'request' },
    bubble: { text: 'Los campos #id, #firstname y los demás no existen fuera de la clase. Eso es encapsulamiento real.' },
  },
  {
    id: 'paso-12-2',
    step: 12,
    part: { n: 2, of: 3, label: 'Getters y setters' },
    phase: 'modelo',
    layer: 'models/',
    title: 'La entidad Persona (POO)',
    file: 'models/Persona.js',
    lead: ['Cada campo tiene un <code>get</code> para leerlo y un <code>set</code> para asignarlo. Los setters limpian espacios con <code>trim()</code> y convierten <code>age</code> a número.'],
    visual: { type: 'editor', tabs: [{ file: 'models/Persona.js', lang: 'javascript', range: [26, 69], focus: [[35, 42]] }] },
    flow: { lit: ['models'], mode: 'request' },
    bubble: { text: 'La única forma de leer o modificar un campo desde afuera es con sus getters y setters públicos: persona.firstname o persona.firstname = "Ana".' },
  },
  {
    id: 'paso-12-3',
    step: 12,
    part: { n: 3, of: 3, label: 'toJSON()' },
    phase: 'modelo',
    layer: 'models/',
    title: 'La entidad Persona (POO)',
    file: 'models/Persona.js',
    lead: ['<code>toJSON()</code> convierte la instancia en un objeto plano, listo para enviarse como JSON en las respuestas de la API.'],
    visual: { type: 'editor', tabs: [{ file: 'models/Persona.js', lang: 'javascript', range: [71, 84], focus: [[73, 81]] }] },
    flow: { lit: ['models'], mode: 'request' },
    bubble: { text: 'El service siempre devuelve persona.toJSON(). Sin este método, JSON.stringify no vería los campos privados y la respuesta llegaría vacía: {}.' },
    mood: 'think',
  },
  {
    id: 'paso-13',
    step: 13,
    phase: 'modelo',
    layer: 'config/',
    title: 'Carga de variables de entorno',
    file: 'config/env.js',
    lead: ['Carga y valida las variables de entorno desde <code>.env</code> con <code>dotenv</code>. Centralizarlo evita repetir <code>require(\'dotenv\').config()</code> en cada archivo.'],
    commands: [{ code: 'touch config/env.js' }],
    visual: { type: 'editor', tabs: [{ file: 'config/env.js', lang: 'javascript', focus: [[13, 17]] }] },
    flow: { lit: ['express', 'mysql'], mode: 'idle' },
    bubble: { text: 'Si falta una variable obligatoria, la app se detiene al arrancar con un mensaje claro, en lugar de fallar más tarde de forma misteriosa.' },
  },
  {
    id: 'paso-14',
    step: 14,
    phase: 'modelo',
    layer: 'config/',
    title: 'Clase de conexión a MySQL',
    file: 'config/database.js',
    lead: ['Una clase con un <strong>pool</strong> de conexiones (<code>mysql2/promise</code>). El pool reutiliza conexiones en vez de abrir y cerrar una nueva por cada consulta: mucho más eficiente para una API.'],
    commands: [{ code: 'touch config/database.js' }],
    visual: { type: 'editor', tabs: [{ file: 'config/database.js', lang: 'javascript', focus: [[30, 34]] }] },
    flow: { lit: ['mysql'], mode: 'request' },
    bubble: { text: 'pool.execute(sql, parametros) usa consultas preparadas: los ? se reemplazan de forma segura por los valores. Así nos protegemos de la inyección SQL.' },
  },

  // ---------------------------------------------------------- CAPAS DE LA API
  {
    id: 'paso-15',
    step: 15,
    phase: 'capas',
    layer: 'middleware/',
    title: 'Manejo centralizado de errores',
    file: 'middleware/errorHandler.js',
    lead: ['En Express, un middleware con <strong>4 parámetros</strong> <code>(err, req, res, next)</code> se reconoce automáticamente como manejador de errores.'],
    commands: [{ code: 'touch middleware/errorHandler.js' }],
    visual: { type: 'editor', tabs: [{ file: 'middleware/errorHandler.js', lang: 'javascript', focus: [[24, 30]] }] },
    flow: { lit: ['middleware'], mode: 'error' },
    bubble: { text: 'Si el error es operacional, el cliente ve su mensaje real. Si es un bug inesperado, se oculta el detalle técnico y se responde con un mensaje genérico, por seguridad.' },
    mood: 'surprised',
  },
  {
    id: 'paso-16-1',
    step: 16,
    part: { n: 1, of: 5, label: 'Importaciones y filaAPersona' },
    phase: 'capas',
    layer: 'services/',
    title: 'Lógica de negocio y CRUD',
    file: 'services/persona.service.js',
    lead: ['Aquí vive la lógica de negocio. El service valida los datos (<code>utils/validators</code>), construye un objeto <code>Persona</code> y usa sus getters para ejecutar las consultas SQL con el pool de conexiones.'],
    commands: [{ code: 'touch services/persona.service.js' }],
    visual: { type: 'editor', tabs: [{ file: 'services/persona.service.js', lang: 'javascript', range: [1, 21], focus: [[18, 21]] }] },
    flow: { lit: ['services', 'utils'], mode: 'request' },
    bubble: { text: 'El service nunca recibe el req ni el res de Express, solo datos simples. Así se puede reutilizar desde un controlador, un script o una prueba automatizada.' },
  },
  {
    id: 'paso-16-2',
    step: 16,
    part: { n: 2, of: 5, label: 'CREATE: crearPersona' },
    phase: 'capas',
    layer: 'services/',
    title: 'Lógica de negocio y CRUD',
    file: 'services/persona.service.js',
    lead: ['Valida, crea el objeto <code>Persona</code> y ejecuta un <code>INSERT</code> usando los getters del objeto como parámetros. MySQL devuelve el id generado en <code>insertId</code>.'],
    visual: { type: 'editor', tabs: [{ file: 'services/persona.service.js', lang: 'javascript', range: [23, 46], focus: [[32, 41]] }] },
    flow: { lit: ['services', 'mysql'], mode: 'request' },
    bubble: { text: 'Fíjate en los ? del INSERT: los valores viajan aparte, en el arreglo parametros, nunca pegados al texto SQL.' },
  },
  {
    id: 'paso-16-3',
    step: 16,
    part: { n: 3, of: 5, label: 'READ: todas y por id' },
    phase: 'capas',
    layer: 'services/',
    title: 'Lógica de negocio y CRUD',
    file: 'services/persona.service.js',
    lead: ['Dos lecturas: todas las personas ordenadas por id, o una sola por su id. Cada fila de la base de datos se convierte en una instancia de <code>Persona</code>.'],
    visual: { type: 'editor', tabs: [{ file: 'services/persona.service.js', lang: 'javascript', range: [48, 65], focus: [[60, 62]] }] },
    flow: { lit: ['services', 'mysql'], mode: 'request' },
    bubble: { text: 'Si el SELECT no devuelve filas, lanzamos un AppError con 404. El controller no tiene que preguntar si la persona existe.' },
  },
  {
    id: 'paso-16-4',
    step: 16,
    part: { n: 4, of: 5, label: 'UPDATE: actualizarPersona' },
    phase: 'capas',
    layer: 'services/',
    title: 'Lógica de negocio y CRUD',
    file: 'services/persona.service.js',
    lead: ['Primero confirma que la persona existe (reutilizando <code>obtenerPersonaPorId</code>), luego valida los datos nuevos y ejecuta el <code>UPDATE</code>.'],
    visual: { type: 'editor', tabs: [{ file: 'services/persona.service.js', lang: 'javascript', range: [67, 92], focus: [[69, 71]] }] },
    flow: { lit: ['services', 'mysql'], mode: 'request' },
    bubble: { text: 'Reutilizar obtenerPersonaPorId nos da el 404 gratis: si el id no existe, el error se lanza antes de intentar actualizar.' },
  },
  {
    id: 'paso-16-5',
    step: 16,
    part: { n: 5, of: 5, label: 'DELETE y exportaciones' },
    phase: 'capas',
    layer: 'services/',
    title: 'Lógica de negocio y CRUD',
    file: 'services/persona.service.js',
    lead: ['Verifica que la persona exista antes de borrarla, para poder responder 404, y exporta las cinco operaciones del CRUD.'],
    visual: { type: 'editor', tabs: [{ file: 'services/persona.service.js', lang: 'javascript', range: [94, 109], focus: [[96, 100]] }] },
    flow: { lit: ['services', 'mysql'], mode: 'request' },
    bubble: { text: 'Con este archivo completo, la lógica del CRUD está lista. Falta conectarla con HTTP: ese es el trabajo del controller.' },
  },
  {
    id: 'paso-17-1',
    step: 17,
    part: { n: 1, of: 4, label: 'Importaciones y POST' },
    phase: 'capas',
    layer: 'controllers/',
    title: 'Entrada y salida HTTP',
    file: 'controllers/persona.controller.js',
    lead: ['El controlador maneja la entrada y salida HTTP de cada endpoint (<code>req</code>/<code>res</code>), delega la lógica al service y responde con el formato JSON estándar de la API.'],
    commands: [{ code: 'touch controllers/persona.controller.js' }],
    visual: { type: 'editor', tabs: [{ file: 'controllers/persona.controller.js', lang: 'javascript', range: [1, 27], focus: [[24, 26]] }] },
    flow: { lit: ['controllers'], mode: 'request' },
    bubble: { text: 'Todos los controladores siguen el patrón try / catch con next(error). Así el error llega al middleware sin repetir el manejo en cada función.' },
  },
  {
    id: 'paso-17-2',
    step: 17,
    part: { n: 2, of: 4, label: 'GET: listar y obtener por id' },
    phase: 'capas',
    layer: 'controllers/',
    title: 'Entrada y salida HTTP',
    file: 'controllers/persona.controller.js',
    lead: ['<code>obtenerPersonas</code> responde 200 con la lista completa. <code>obtenerPersonaPorId</code> valida primero el id de la URL y luego consulta al service.'],
    visual: { type: 'editor', tabs: [{ file: 'controllers/persona.controller.js', lang: 'javascript', range: [29, 63], focus: [[49, 51]] }] },
    flow: { lit: ['controllers'], mode: 'request' },
    bubble: { text: 'Un id como "abc" se rechaza aquí con un 400, antes de llegar a la base de datos.' },
  },
  {
    id: 'paso-17-3',
    step: 17,
    part: { n: 3, of: 4, label: 'PUT: actualizar' },
    phase: 'capas',
    layer: 'controllers/',
    title: 'Entrada y salida HTTP',
    file: 'controllers/persona.controller.js',
    lead: ['Recibe el id por la URL y los datos nuevos en el body. Si todo sale bien, responde 200 con la persona actualizada.'],
    visual: { type: 'editor', tabs: [{ file: 'controllers/persona.controller.js', lang: 'javascript', range: [65, 84], focus: [[74, 74]] }] },
    flow: { lit: ['controllers'], mode: 'request' },
    bubble: { text: 'PUT reemplaza el recurso completo: el body debe traer los cuatro campos, firstname, lastname, age y datebirth.' },
  },
  {
    id: 'paso-17-4',
    step: 17,
    part: { n: 4, of: 4, label: 'DELETE y exportaciones' },
    phase: 'capas',
    layer: 'controllers/',
    title: 'Entrada y salida HTTP',
    file: 'controllers/persona.controller.js',
    lead: ['Elimina la persona y responde con <code>data: null</code>. Luego exporta los cinco controladores para usarlos en las rutas.'],
    visual: { type: 'editor', tabs: [{ file: 'controllers/persona.controller.js', lang: 'javascript', range: [86, 113], focus: [[95, 95]] }] },
    flow: { lit: ['controllers'], mode: 'request' },
    bubble: { text: 'Cada función del controller recibe (req, res, next). Es exactamente la firma que Express espera de un manejador de ruta.' },
  },
  {
    id: 'paso-18',
    step: 18,
    phase: 'capas',
    layer: 'routes/',
    title: 'Definición de endpoints',
    file: 'routes/persona.routes.js',
    lead: ['Define los endpoints del recurso persona y los conecta con su método del controller. El router se monta en <code>config/app.js</code> bajo el prefijo <code>/api/personas</code>.'],
    commands: [{ code: 'touch routes/persona.routes.js' }],
    endpoints: [
      ['POST', '/api/personas', 'Crear una nueva persona'],
      ['GET', '/api/personas', 'Listar todas las personas'],
      ['GET', '/api/personas/:id', 'Obtener una persona por su id'],
      ['PUT', '/api/personas/:id', 'Actualizar una persona existente'],
      ['DELETE', '/api/personas/:id', 'Eliminar una persona'],
    ],
    visual: { type: 'editor', tabs: [{ file: 'routes/persona.routes.js', lang: 'javascript', focus: [[13, 26]] }] },
    flow: { lit: ['routes'], mode: 'request' },
    bubble: { text: 'Las rutas son relativas: "/" aquí equivale a /api/personas, porque el prefijo se agrega al montar el router en config/app.js.' },
  },
  {
    id: 'paso-19',
    step: 19,
    phase: 'capas',
    layer: 'config/',
    title: 'Configuración de Express',
    file: 'config/app.js',
    lead: ['Registra los middlewares globales y monta las rutas. Se separa de <code>index.js</code> para aislar la configuración de la app del arranque del servidor.'],
    commands: [{ code: 'touch config/app.js' }],
    visual: { type: 'editor', tabs: [{ file: 'config/app.js', lang: 'javascript', focus: [[27, 32]] }] },
    flow: { lit: ['express', 'middleware'], mode: 'request' },
    bubble: { text: 'El orden de los app.use() importa: las rutas van primero y los middlewares de error siempre al final, porque Express los ejecuta en el orden en que se registran.' },
  },
  {
    id: 'paso-20',
    step: 20,
    phase: 'capas',
    layer: 'raíz',
    title: 'Punto de entrada de la aplicación',
    file: 'index.js',
    lead: ['Su única responsabilidad es arrancar el servidor: verifica la conexión a MySQL y luego pone a Express a escuchar peticiones en el puerto configurado.'],
    commands: [{ code: 'touch index.js' }],
    visual: { type: 'editor', tabs: [{ file: 'index.js', lang: 'javascript', focus: [[14, 16]] }] },
    flow: { lit: ['express', 'mysql'], mode: 'boot' },
    bubble: { text: 'Falla rápido: si MySQL no está disponible, el servidor no arranca a medias. Muestra el error y termina con process.exit(1).' },
  },

  // ---------------------------------------------------------- PROBAR Y CERRAR
  {
    id: 'paso-21',
    step: 21,
    phase: 'probar',
    layer: 'terminal',
    title: 'Ejecutar el servidor',
    lead: ['Con todos los archivos listos, inicia el servidor en modo desarrollo.'],
    commands: [{ code: 'npm run dev' }],
    visual: {
      type: 'output',
      title: 'Si todo está bien configurado, verás en la consola:',
      command: 'npm run dev',
      lines: [
        'Conexion a MySQL establecida correctamente.',
        'Servidor persona-api escuchando en http://localhost:3000',
        'Endpoints disponibles en http://localhost:3000/api/personas',
      ],
    },
    flow: { lit: ['cliente', 'express', 'routes', 'controllers', 'services', 'models', 'mysql'], mode: 'boot' },
    bubble: { text: 'Si en lugar de esto ves "Access denied for user", revisa DB_USER y DB_PASSWORD en tu archivo .env.' },
  },
  {
    id: 'paso-22',
    step: 22,
    phase: 'probar',
    layer: 'curl',
    title: 'Probar los endpoints con curl',
    lead: ['Con el servidor corriendo, abre <strong>otra terminal</strong> y prueba cada operación del CRUD. Elige una petición y presiona <strong>Enviar</strong> para ver su recorrido por las capas.'],
    visual: { type: 'tester', requests: REQUESTS },
    flow: { lit: [], mode: 'idle' },
    bubble: { text: 'Todas las respuestas tienen el mismo formato: success, message y data. Así el cliente siempre sabe dónde buscar la información.' },
  },
  {
    id: 'paso-23',
    step: 23,
    phase: 'probar',
    layer: 'postman/',
    title: 'Probar con Postman o Thunder Client',
    file: 'postman/Persona_API.postman_collection.json',
    lead: ['El proyecto incluye una colección lista para importar, con una petición de ejemplo para cada endpoint y la variable <code>{{base_url}}</code> apuntando a <code>http://localhost:3000</code>.'],
    list: [
      '<strong>Postman:</strong> botón <em>Import</em> y selecciona el archivo <code>.json</code> de la carpeta <code>postman/</code>.',
      '<strong>Thunder Client (VS Code):</strong> pestaña <em>Collections</em>, luego <em>Import</em> y selecciona el mismo archivo.',
    ],
    visual: {
      type: 'collection',
      name: 'Persona API',
      variable: ['base_url', 'http://localhost:3000'],
      items: [
        ['POST', 'Crear persona', '{{base_url}}/api/personas'],
        ['GET', 'Obtener todas las personas', '{{base_url}}/api/personas'],
        ['GET', 'Obtener persona por id', '{{base_url}}/api/personas/1'],
        ['PUT', 'Actualizar persona', '{{base_url}}/api/personas/1'],
        ['DELETE', 'Eliminar persona', '{{base_url}}/api/personas/1'],
      ],
    },
    flow: { lit: ['cliente'], mode: 'idle' },
    bubble: { text: 'Postman y Thunder Client guardan tus peticiones, así no tienes que reescribir cada comando curl.' },
  },
  {
    id: 'paso-24',
    step: 24,
    phase: 'probar',
    layer: 'resumen',
    title: 'La arquitectura final',
    lead: ['Así queda <code>persona-api</code>. Cada carpeta es una capa, y una petición las atraviesa en orden hasta llegar a MySQL.'],
    leftVisual: 'architecture',
    visual: { type: 'explorer', title: 'persona-api completo', tree: TREE_FINAL },
    flow: { lit: [], mode: 'full' },
    bubble: { text: 'Una petición entra por routes, pasa por controllers y services, usa el modelo Persona y llega a MySQL. La respuesta hace el camino de vuelta.' },
  },
  {
    id: 'paso-25',
    step: 25,
    kind: 'final',
    phase: 'probar',
    layer: 'retos',
    title: 'Ejercicios propuestos',
    lead: ['Retos para seguir practicando con tu API:'],
    ordered: [
      'Agregar un endpoint <code>GET /api/personas/buscar?nombre=...</code> que filtre personas por <code>firstname</code> usando <code>LIKE</code> en la consulta SQL.',
      'Agregar paginación al endpoint <code>GET /api/personas</code> (<code>?pagina=1&amp;limite=10</code>).',
      'Agregar una validación de negocio: que <code>age</code> sea coherente con <code>datebirth</code> (por ejemplo, con un margen de +/- 1 año).',
      'Investigar cómo proteger esta API con un middleware de autenticación (por ejemplo, JSON Web Tokens) antes de llegar a las rutas de <code>persona</code>.',
      'Escribir pruebas automatizadas de los endpoints con <code>jest</code> y <code>supertest</code>.',
    ],
    visual: { type: 'celebrate' },
    flow: { lit: ['cliente', 'express', 'routes', 'controllers', 'services', 'models', 'mysql', 'utils', 'middleware'], mode: 'boot' },
    bubble: { title: '¡Lo lograste!', text: 'Tu API REST de Persona está completa. Elige un reto y sigue practicando. Haz clic en mí para celebrar otra vez.' },
    mood: 'celebrate',
  },
];
